-- MySQL Script generated by MySQL Workbench
-- mar. 04 juin 2019 15:49:05 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`capteur_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`capteur_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`capteur_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCapteur_Type_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`capteur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`capteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `capteur_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCapteur_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_capteur_capteur_type1_idx` (`capteur_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_capteur_capteur_type1`
    FOREIGN KEY (`capteur_type_id`)
    REFERENCES `mydb`.`capteur_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capteur_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`capteur_value` ;

CREATE TABLE IF NOT EXISTS `mydb`.`capteur_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `capteur_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_capteur_value_capteur_idx` (`capteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_capteur_value_capteur`
    FOREIGN KEY (`capteur_id`)
    REFERENCES `mydb`.`capteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
